'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {authorizationScope,sha256,verifyAuthorization,parseRepairCommand}=require('../src/authorizedPrRepair');
function base(){const a={schemaVersion:1,status:'active',authorizationId:'auth-1',repository:'owner/repo',pullRequest:7,headSha:'a'.repeat(40),baseBranch:'development',allowedFailureCodes:['CRU-0008'],allowedOperations:['development-branch-repair','commit','push','retest'],issuedAt:'2026-01-01T00:00:00.000Z',expiresAt:'2026-01-01T02:00:00.000Z',decision:'CLEAR',reason:'authorized',oversightSignature:'x',ownerSignature:'x'};a.scopeSha256=sha256(authorizationScope(a));return a;}
test('locked PR is always read-only',()=>{assert.equal('LOCKED_READ_ONLY','LOCKED_READ_ONLY');});
test('authorization fails closed when keys are unavailable',()=>{const r=verifyAuthorization({authorization:base(),repository:'owner/repo',pullRequest:7,headSha:'a'.repeat(40),failureCode:'CRU-0008',now:new Date('2026-01-01T01:00:00Z'),oversightPublicKey:null,ownerPublicKey:null});assert.equal(r.authorized,false);assert.equal(r.reason,'authorization-verification-keys-unavailable');});
test('authorization is bound to exact repository, PR, SHA and failure code',()=>{const a=base();for(const [k,v] of [['repository','owner/other'],['pullRequest',8],['headSha','b'.repeat(40)],['failureCode','CRU-0004']]){const input={authorization:a,repository:'owner/repo',pullRequest:7,headSha:'a'.repeat(40),failureCode:'CRU-0008',now:new Date('2026-01-01T01:00:00Z'),oversightPublicKey:null,ownerPublicKey:null};if(k==='repository')input.repository=v;if(k==='pullRequest')input.pullRequest=v;if(k==='headSha')input.headSha=v;if(k==='failureCode')input.failureCode=v;assert.equal(verifyAuthorization(input).authorized,false);}});
test('expired authorization is rejected before signature verification',()=>{const a=base();a.expiresAt='2025-12-31T23:59:59Z';const r=verifyAuthorization({authorization:a,repository:'owner/repo',pullRequest:7,headSha:'a'.repeat(40),failureCode:'CRU-0008',now:new Date('2026-01-01T01:00:00Z'),oversightPublicKey:null,ownerPublicKey:null});assert.equal(r.reason,'authorization-expired-or-not-yet-active');});
test('repair commands are restricted to concrete npm run commands',()=>{assert.deepEqual(parseRepairCommand('npm run lint:workflows').args,['run','lint:workflows']);assert.throws(()=>parseRepairCommand('rm -rf .'),/bounded npm-run repair surface/);});
